Repository Team-INSERT/IOJ_WEB, pull requests merged in 2024-08, with the labels that each got.

#48 대회 API 연결
  src/app/App.tsx
  src/pages/admin/api/constProblemList.ts
  src/pages/admin/ui/main/page.tsx
  src/pages/game/api/gameApi.ts
  src/pages/gameRanking/index.tsx
  src/pages/gameRanking/ui/page/page.tsx
  src/pages/room/api/roomApi.ts
  src/pages/room/ui/Contest/List/index.tsx
  src/pages/room/ui/Contest/List/style.ts
  src/pages/room/ui/Contest/Question/index.tsx
  src/pages/room/ui/Contest/Rank/index.tsx
  src/pages/room/ui/Contest/Rank/style.ts
  src/shared/components/Question/index.tsx
  src/shared/components/Question/style.ts
  src/shared/components/QuestionCategory/index.tsx
Labels: ✨ Feature

#43 모달 개발
  src/assets/correct.svg
  src/assets/warning.svg
  src/pages/admin/ui/main/page.tsx
  src/pages/main/ui/page/Page.tsx
  src/shared/components/Button.tsx
  src/shared/components/Modal/index.tsx
  src/shared/components/Modal/style.ts
Labels: ✨ Feature

#49 어드민 페이지 퍼블리싱
  src/app/App.tsx
  src/assets/Check.svg
  src/assets/Minus.svg
  src/assets/Out.png
  src/assets/Plus.svg
  src/pages/admin/api/contestCreate.ts
  src/pages/admin/index.tsx
  src/pages/admin/ui/createQ/index.tsx
  src/pages/admin/ui/createQ/style.ts
  src/pages/admin/ui/main/index.tsx
  src/pages/admin/ui/start/index.tsx
  src/pages/admin/ui/start/style.ts
  src/shared/components/Stars.tsx
  src/shared/components/index.tsx
  src/shared/components/level.tsx
  src/shared/style/globalStyle.ts
  src/shared/style/index.ts
Labels: ✨ Feature

#52 대회 권한 에러 핸들링
  src/app/App.tsx
  src/pages/room/index.tsx
  src/pages/room/ui/Contest/Question/index.tsx
  src/shared/components/ErrorModal.tsx
Labels: ✨ Feature

#39 인 게임 API 연결
  src/pages/admin/api/problem.ts
  src/pages/game/api/contestSubmt.ts
  src/pages/game/api/execution.ts
  src/pages/game/api/gameDetail.ts
  src/pages/game/api/gameList.ts
  src/pages/game/api/gameSubmit.ts
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/editor/style.ts
  src/pages/game/ui/problem/index.tsx
  src/pages/game/ui/problem/style.ts
  src/shared/components/DropDown.tsx
  src/shared/components/index.tsx
  tsconfig.json
Labels: ✨ Feature

#58 문제 페이지로 넘어가는 경로 변경
  src/app/App.tsx
  src/pages/room/ui/Contest/Question/index.tsx
Labels: 📄 Docs

#61 인 게임 페이지 마무리
  src/pages/game/api/contestSubmt.ts
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/editor/style.ts
  src/pages/game/ui/index.tsx
  src/pages/game/ui/problem/style.ts
  src/pages/game/ui/testbox/index.tsx
  src/pages/game/ui/testbox/style.ts
  src/pages/main/ui/page/Page.tsx
  src/pages/room/ui/Contest/List/index.tsx
  src/pages/room/ui/Contest/Question/style.ts
  src/shared/components/DropDown.tsx
  src/shared/components/GameHeader/index.tsx
  src/shared/components/GameHeader/style.ts
Labels: ✨ Feature

#63 인 게임 페이지 기타 수정 사항
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/problem/style.ts
  src/shared/components/Button.tsx
  src/shared/components/DropDown.tsx
Labels: ✨ Feature

#72 게임헤더 퍼블리싱 수정
  src/shared/components/GameHeader/index.tsx
Labels: ✨ Feature

#74 결과 순위페이지 퍼블리싱,기능 수정 완료
  src/pages/main/ui/page/Page.tsx
  src/pages/room/ui/Contest/Question/index.tsx
  src/pages/room/ui/Contest/Rank/index.tsx
  src/pages/room/ui/Contest/Rank/style.ts
  src/pages/room/ui/GameHome/index.tsx
  src/pages/room/ui/GameHome/style.ts
  src/shared/components/MainHeader/index.tsx
Labels: 🐞 Bug, ✨ Feature

#76 제출 클릭 시 에러 해결
  src/pages/game/api/contestSubmt.ts
  src/pages/game/interfaces/gameInterfaces.ts
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/testbox/index.tsx
Labels: 🐞 Bug, 📪 API
