Repository Team-INSERT/IOJ_WEB, pull requests merged in 2024-10, with the labels that each got.

#170 web title, favicon 적용
  public/index.html
  public/insertLogo.svg
  public/logo.svg
Labels: ✨ Feature

#172 사파리 폰트 안됨 이슈 해결
  src/index.css
Labels: 🐞 Bug, 🔮 Modification

#178 코드 저장 버튼 추가
  src/pages/game/ui/editor/index.tsx
Labels: 🐞 Bug, 🔨 Refactor, ✨ Feature, 🔥 HotFix

#177 페이지 리사이징
  package-lock.json
  package.json
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/editor/style.ts
  src/pages/game/ui/index.tsx
  src/pages/game/ui/problem/style.ts
Labels: ✨ Feature

#175 애니메이션 위치 오류 해결
  src/shared/components/Submit.tsx
Labels: 🐞 Bug, 🔥 HotFix, 🔮 Modification

#181 초기화 버튼 추가
  src/pages/game/ui/editor/index.tsx
  src/shared/components/Submit.tsx
Labels: ✨ Feature

#187 랭킹 채점기준 퍼블리싱 및 랭킹페이지 퍼블리싱 수정
  pnpm-lock.yaml
  src/assets/CircleExit.svg
  src/pages/room/ui/contestRank/index.tsx
  src/pages/room/ui/contestRank/style.ts
  src/shared/components/Button.tsx
  src/shared/components/ScoreStandard/index.tsx
  src/shared/components/ScoreStandard/style.ts
Labels: ✨ Feature, 🔮 Modification

#191 실행 터미널에 결과값이 모두 나오지 않는 문제 해결
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/testbox/index.tsx
  src/shared/hooks/useTerminal.ts
  src/shared/hooks/useWebSocket.ts
Labels: 🔥 HotFix, 🔮 Modification

#190 auth 로직 변경
  src/pages/game/ui/index.tsx
  src/shared/components/GameHeader/index.tsx
  src/shared/utils/cookie/cookie.ts
  src/shared/utils/customAxios.ts
Labels: 🔨 Refactor, 🔮 Modification

#195 문제 포함 페이지에 출처추가
  .idea/inspectionProfiles/Project_Default.xml
  src/pages/admin/ui/createQ/index.tsx
  src/pages/admin/ui/createQ/style.ts
  src/pages/game/interfaces/gameInterfaces.ts
  src/pages/game/ui/index.tsx
  src/pages/game/ui/problem/index.tsx
  src/pages/problem/ui/problemDetail/index.tsx
  src/pages/problem/ui/problemDetail/style.ts
  src/pages/problem/ui/problemList/index.tsx
  src/pages/problem/ui/problemList/style.ts
  src/shared/helper/validateQuestion.ts
  src/shared/utils/customAxios.ts
Labels: ✨ Feature, 🔮 Modification

#197 refreshToken 401 에러 전역 모달 처리
  .eslintrc
  package.json
  pnpm-lock.yaml
  src/app/App.tsx
  src/shared/utils/atom/modalAtom.ts
  src/shared/utils/customAxios.ts
Labels: 🔨 Refactor, ✨ Feature, 🔮 Modification

#199 Add: 저장 시 모달 띄우기
  src/pages/game/ui/editor/index.tsx
Labels: ✨ Feature

#194 터미널에 실행 결과값이 계단 형식으로 뜨는 이슈 해결
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/testbox/index.tsx
  src/shared/hooks/useTerminal.ts
  src/shared/hooks/useWebSocket.ts
Labels: 🐞 Bug, 🔥 HotFix, 🔮 Modification

#200 아이템 공격 대상 선택 페이지
  src/assets/Character.tsx
  src/assets/InGameHoverUserPartment.svg
  src/assets/InGameUserPartment.svg
  src/assets/chooseAttackBackground.svg
  src/pages/game/ui/chooseAttackModal/index.tsx
  src/pages/game/ui/chooseAttackModal/style.ts
  src/shared/components/InGame/UserCompartment/index.tsx
  src/shared/components/InGame/UserCompartment/style.ts
Labels: ✨ Feature

#203 아이템 컴포넌트 퍼블리싱
  src/shared/components/Item/index.tsx
  src/shared/components/Item/style.ts
Labels: ✨ Feature
