Repository Team-INSERT/IOJ_WEB, pull requests merged in 2024-09, with the labels that each got.

#78 제출버튼 연속클릭 방지
  src/pages/game/api/testcase.ts
  src/pages/game/interfaces/gameInterfaces.ts
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/index.tsx
  src/pages/game/ui/problem/index.tsx
  src/pages/game/ui/testbox/index.tsx
Labels: ✨ Feature

#88 인 게임 코드 에디터 자동완성
  craco.config.cjs
  package.json
  pnpm-lock.yaml
  public/index.html
  src/pages/game/ui/editor/index.tsx
  src/shared/components/boiler.ts
Labels: 🐞 Bug, 🔨 Refactor

#90 AI 분석 페이지 퍼블리싱
  package-lock.json
  package.json
  src/app/App.tsx
  src/assets/BlueStar.tsx
  src/assets/Star.tsx
  src/assets/Tag.svg
  src/pages/game/ai/ui/page/page.tsx
  src/pages/game/ai/ui/page/style.ts
  src/shared/components/Stars.tsx
Labels: ✨ Feature

#92 드롭다운 에러 및 자동완성 에러 해결
  src/pages/game/ui/editor/index.tsx
  src/shared/components/DropDown.tsx
Labels: 🐞 Bug, 🔥 HotFix, 🔮 Modification

#94 에러 모달 띄우고, 404 페이지 처리
  src/app/App.tsx
  src/pages/game/ui/editor/index.tsx
  src/pages/not-found/Not-found.tsx
  src/pages/not-found/style.ts
  src/shared/components/ErrorModal.tsx
Labels: 🔨 Refactor, ✨ Feature

#98 문제 실행 API 연결
  package-lock.json
  package.json
  src/pages/game/interfaces/gameInterfaces.ts
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/testbox/index.tsx
  src/pages/game/ui/testbox/style.ts
  src/shared/hooks/useWebSocket.ts
Labels: ✨ Feature, 📪 API

#97 제출 결과 모달 기능 구현
  src/assets/CorrectModal.svg
  src/assets/Submit.svg
  src/pages/game/ui/editor/index.tsx
  src/shared/components/Stars.tsx
  src/shared/components/Submit.tsx
  src/shared/components/index.tsx
Labels: ✨ Feature

#117 제출현황 버튼 삭제
  src/shared/components/GameHeader/index.tsx
Labels: 🔮 Modification

#118 어드민페이지 대회 문제input 수정
  .idea/prettier.xml
  pnpm-lock.yaml
  src/pages/admin/ui/createC/index.tsx
  src/shared/helper/index.ts
  src/shared/helper/todayDateHelper.ts
  src/shared/helper/validateContestHelper.ts
Labels: 🐞 Bug

#120 남은 시간 가운데 배치
  src/shared/components/GameHeader/style.ts
Labels: 🔮 Modification

#123 실행 endpoint 변경
  src/pages/game/ui/editor/index.tsx
  src/shared/hooks/useWebSocket.ts
Labels: 📪 API

#124 구글 로그인 시 로딩 창 추가
  src/app/App.tsx
  src/pages/loading/index.tsx
  src/pages/loading/style.ts
Labels: ✨ Feature

#126 accessToken 관련 문제 수정
  package.json
  src/pages/admin/ui/createQ/style.ts
  src/pages/room/ui/Contest/List/index.tsx
  src/shared/components/GameHeader/index.tsx
  src/shared/components/MainHeader/index.tsx
  src/shared/utils/customAxios.ts
Labels: 🐞 Bug

#131 문제리스트 페이지 퍼블리싱, api 연결 및 문제상세페이지 연결
  src/app/App.tsx
  src/assets/Search.svg
  src/pages/game/ui/problem/style.ts
  src/pages/problem/api/problem.ts
  src/pages/problem/api/problemList.ts
  src/pages/problem/index.tsx
  src/pages/problem/ui/problemDetail/index.tsx
  src/pages/problem/ui/problemDetail/style.ts
  src/pages/problem/ui/problemList/index.tsx
  src/pages/problem/ui/problemList/style.ts
  src/shared/components/MainHeader/index.tsx
  src/shared/components/Question/index.tsx
  src/shared/components/Question/style.ts
  src/shared/components/Stars.tsx
Labels: ✨ Feature, 🔮 Modification

#141 게임찾기 페이지 퍼블리싱
  src/app/App.tsx
  src/pages/room/index.tsx
  src/pages/room/ui/contestList/index.tsx
  src/pages/room/ui/contestList/style.ts
  src/pages/room/ui/contestQuestion/index.tsx
  src/pages/room/ui/contestQuestion/style.ts
  src/pages/room/ui/contestRank/index.tsx
  src/pages/room/ui/contestRank/style.ts
  src/pages/room/ui/gameFind/index.tsx
  src/pages/room/ui/gameFind/style.ts
  src/shared/components/Room/index.tsx
  src/shared/components/Room/style.ts
  src/shared/components/boiler.ts
Labels: ✨ Feature

#132 에디터 길이 동적 조절
  package.json
  pnpm-lock.yaml
  src/pages/game/ui/editor/index.tsx
  src/pages/room/index.tsx
Labels: 🐞 Bug, 🔨 Refactor, 🔮 Modification

#144 언어 바들바들 거림 해결
  src/pages/game/ui/editor/index.tsx
Labels: 🐞 Bug, 🔥 HotFix, 🔮 Modification

#145 방 생성 모달 개발
  src/assets/XBold.svg
  src/pages/room/ui/createRoomModal/index.tsx
  src/pages/room/ui/createRoomModal/style.ts
  src/pages/room/ui/gameFind/index.tsx
Labels: ✨ Feature

#138 보일러플레이트 코드 API 연결 및 설정
  .idea/jsLinters/eslint.xml
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/pages/game/api/boilerplateCode.ts
  src/pages/game/ui/editor/index.tsx
  src/pages/main/ui/page/Page.tsx
  src/pages/room/index.tsx
  src/shared/components/MainHeader/style.ts
Labels: ✨ Feature, 📪 API

#147 폴더 명 변경 후, 원격 저장소에 변경되지 않는 이슈 해결
  src/pages/room/ui/gameHome/index.tsx
  src/pages/room/ui/gameHome/style.ts
Labels: 🐞 Bug, 🔥 HotFix

#133 준비 중인 페이지 처리
  src/app/App.tsx
  src/pages/prepare/index.tsx
  src/pages/prepare/style.ts
Labels: 🔨 Refactor, 🔮 Modification

#135 대회 별 코드 저장
  src/pages/game/ui/editor/index.tsx
  src/shared/components/DropDown.tsx
Labels: 🔨 Refactor, 🔥 HotFix, 🔮 Modification

#143 게임 대기실 화면 퍼블리싱
  src/app/App.tsx
  src/assets/Character.tsx
  src/assets/InGameHoverUserPartment.svg
  src/assets/InGameUserPartment.svg
  src/assets/Ready.svg
  src/pages/waiting/index.tsx
  src/pages/waiting/ui/index.tsx
  src/pages/waiting/ui/style.ts
  src/shared/components/InGame/UserCompartment/style.ts
Labels: ✨ Feature

#136 재실행이 되지 않는 버그 수정
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/testbox/index.tsx
  src/shared/hooks/useWebSocket.ts
Labels: 🔮 Modification

#151 Tab이 execution이 아닐때 실행 클릭시 터미널이 열리지 않는 버그 수정
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/testbox/index.tsx
Labels: 🐞 Bug, 🔥 HotFix

#152 파일 확장자 에러
  src/pages/game/ui/editor/style.ts
  src/pages/game/ui/index.tsx
  src/shared/components/DropDown.tsx
  src/shared/components/GameHeader/style.ts
Labels: 🐞 Bug, 🔥 HotFix, 🔮 Modification

#156 보일러 플레이트 & 작성코드 저장
  src/pages/game/ui/editor/index.tsx
Labels: 🐞 Bug, 🔥 HotFix, 🔮 Modification

#159 대회 랭킹페이지 퍼블리싱 수정 및 로딩처리
  src/pages/game/interfaces/gameInterfaces.ts
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/problem/style.ts
  src/pages/game/ui/testbox/index.tsx
  src/pages/room/ui/contestQuestion/index.tsx
  src/pages/room/ui/contestRank/index.tsx
  src/pages/room/ui/contestRank/style.ts
  src/shared/components/ErrorModal.tsx
Labels: 🐞 Bug, 🔨 Refactor, ✨ Feature, 🔮 Modification

#157 에디터 길이 동적 조절
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/editor/style.ts
  src/pages/game/ui/index.tsx
  src/pages/game/ui/testbox/style.ts
Labels: 🐞 Bug, 🔥 HotFix, 🔮 Modification

#163 대회 남은시간, 인게임 남은시간 로딩시간 개선
  src/pages/room/ui/contestQuestion/index.tsx
  src/shared/components/GameHeader/index.tsx
Labels: 🔨 Refactor, 🔮 Modification

#165 모달 생성 및 헤더 변경
  src/pages/admin/ui/createQ/index.tsx
  src/shared/components/MainHeader/index.tsx
  src/shared/helper/validateQuestion.ts
Labels: 🔨 Refactor, 🔥 HotFix, 🔮 Modification
