Repository Team-INSERT/IOJ_WEB, pull requests merged in 2024-07, with the labels that each got.

#6 Add : 절대경로 설정
  tsconfig.json
Labels: ⚙️ Setting

#10 Feat : 공통 컴포넌트 개발
  src/assets/BasicBackground.svg
  src/assets/BasicMarkUp.png
  src/assets/BlueStar.tsx
  src/assets/Character.tsx
  src/assets/Clock.tsx
  src/assets/Close.tsx
  src/assets/Contest.svg
  src/assets/ContestBackground.svg
  src/assets/ContestLogo.tsx
  src/assets/ContestMaskUp.png
  src/assets/ContestTitle.svg
  src/assets/Crown.tsx
  src/assets/CustomBackground.svg
  src/assets/CustomLogo.tsx
  src/assets/CustomMaskUp.png
  src/assets/Customization.svg
  src/assets/GithubLogo.tsx
  src/assets/InGameHoverUserPartment.svg
  src/assets/InGameUserPartment.svg
  src/assets/InsertLogo.tsx
  src/assets/IojLogo.tsx
  src/assets/NoneUser.svg
  src/assets/Problem.tsx
  src/assets/QuestinCategory.tsx
  src/assets/Rectangle 75.svg
  src/assets/Star.tsx
  src/assets/UserCompartment.svg
  src/index.css
  src/shared/components/Button.tsx
  src/shared/components/GameCard/index.tsx
  src/shared/components/GameCard/style.ts
  src/shared/components/GameHeader/index.tsx
  src/shared/components/GameHeader/style.ts
  src/shared/components/InGame/ContestTitle/index.tsx
  src/shared/components/InGame/ContestTitle/style.ts
  src/shared/components/InGame/Result/index.tsx
  src/shared/components/InGame/Result/style.ts
  src/shared/components/InGame/UserCompartment/index.tsx
  src/shared/components/InGame/UserCompartment/style.ts
  src/shared/components/MainHeader/index.tsx
  src/shared/components/MainHeader/style.ts
  src/shared/components/Question/index.tsx
  src/shared/components/Question/style.ts
  src/shared/components/Room/index.tsx
  src/shared/components/Room/style.ts
  src/shared/components/Stars.tsx
  src/shared/components/WaitingRoom/index.tsx
  src/shared/components/WaitingRoom/style.ts
  src/shared/components/footer/index.tsx
  src/shared/components/footer/style.ts
  src/shared/components/header/index.tsx
  src/shared/components/header/style.ts
  src/shared/style/theme.ts
Labels: ✨ Feature

#11 절대경로 추가
  craco.config.js
  package.json
  pnpm-lock.yaml
  src/pages/main/ui/page/Page.tsx
  tsconfig.json
  tsconfig.paths.json
  webpack.config.js
Labels: 🔥 HotFix

#13 홈페이지 개발
  Craco.config.js
  pnpm-lock.yaml
  src/assets/Person.tsx
  src/index.css
  src/pages/main/ui/page/Page.tsx
  src/pages/main/ui/page/style.ts
  src/shared/components/MainHeader/index.tsx
  src/shared/components/MainHeader/style.ts
  src/shared/style/globalStyle.ts
  tsconfig.paths.json
Labels: ✨ Feature

#18 font weight 수정완료
  src/shared/style/font.ts
Labels: 🔥 HotFix

#20 QuestionCategory 컴포넌트화
  src/assets/QuestinCategory.tsx
  src/shared/components/Question/index.tsx
  src/shared/components/QuestionCategory/QuestionCategory.tsx
  src/shared/components/QuestionCategory/style.ts
Labels: ✨ Feature

#23 eslint 설정 및 코드수정
  .eslintrc
  .prettierignore
  .prettierrc
  craco.config.cjs
  craco.config.js
  package.json
  pnpm-lock.yaml
  src/app/App.tsx
  src/assets/AllQuestionsLogo.tsx
  src/assets/BlueStar.tsx
  src/assets/Character.tsx
  src/assets/Clock.tsx
  src/assets/Close.tsx
  src/assets/ContestLogo.tsx
  src/assets/Crown.tsx
  src/assets/CustomLogo.tsx
  src/assets/GameRankBlue.tsx
  src/assets/GameRankGrey.tsx
  src/assets/GithubLogo.tsx
  src/assets/HistoryLogo.tsx
  src/assets/InsertLogo.tsx
  src/assets/IojLogo.tsx
  src/assets/Person.tsx
  src/assets/Problem.tsx
  src/assets/QuestinCategory.tsx
  src/assets/Star.tsx
  src/pages/gameRanking/index.tsx
  src/pages/gameRanking/ui/page/page.tsx
  src/pages/gameRanking/ui/page/style.ts
  src/pages/main/ui/page/Page.tsx
  src/pages/main/ui/page/style.ts
  src/shared/components/Button.tsx
  src/shared/components/GameCard/index.tsx
  src/shared/components/GameCard/style.ts
  src/shared/components/GameHeader/index.tsx
  src/shared/components/GameHeader/style.ts
  src/shared/components/InGame/ContestTitle/index.tsx
  src/shared/components/InGame/ContestTitle/style.ts
  src/shared/components/InGame/Result/index.tsx
  src/shared/components/InGame/UserCompartment/index.tsx
  src/shared/components/InGame/UserCompartment/style.ts
  src/shared/components/MainHeader/index.tsx
  src/shared/components/Question/index.tsx
  src/shared/components/Question/style.ts
  src/shared/components/Room/index.tsx
  src/shared/components/Room/style.ts
  src/shared/components/Stars.tsx
  src/shared/components/WaitingRoom/index.tsx
  src/shared/components/footer/index.tsx
  src/shared/components/footer/style.ts
  src/shared/components/index.tsx
  tsconfig.json
Labels: 🔨 Refactor, ⚙️ Setting

#15 로그인페이지 개발
  src/app/App.tsx
  src/assets/Google.tsx
  src/index.css
  src/pages/login/index.tsx
  src/pages/login/ui/page/Page.tsx
  src/pages/login/ui/page/style.ts
  src/shared/components/MainHeader/index.tsx
  src/shared/components/MainHeader/style.ts
  src/shared/components/QuestionCategory/QuestionCategory.tsx
  src/shared/components/QuestionCategory/style.ts
Labels: ✨ Feature

#21 Feat : 방 개발
  src/assets/GameCardHover.svg
  src/pages/main/ui/page/Page.tsx
  src/pages/room/ui/Contest/List/index.tsx
  src/pages/room/ui/Contest/List/style.ts
  src/pages/room/ui/Contest/Question/index.tsx
  src/pages/room/ui/Contest/Question/style.ts
  src/pages/room/ui/GameHome/index.tsx
  src/pages/room/ui/GameHome/style.ts
  src/shared/components/GameCard/index.tsx
  src/shared/components/GameCard/style.ts
  src/shared/components/InGame/ContestTitle/style.ts
  src/shared/components/Question/style.ts
  src/shared/components/index.tsx
Labels: ✨ Feature

#25 Feat/#5 인게임 페이지 개발
  package-lock.json
  package.json
  pnpm-lock.yaml
  public/index.html
  src/app/App.tsx
  src/index.css
  src/pages/game/index.tsx
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/editor/style.ts
  src/pages/game/ui/index.tsx
  src/pages/game/ui/page/Page.tsx
  src/pages/game/ui/page/style.ts
  src/pages/game/ui/problem/index.tsx
  src/pages/game/ui/problem/style.ts
  src/pages/game/ui/testbox/index.tsx
  src/pages/game/ui/testbox/style.ts
  src/pages/gameRanking/ui/page/page.tsx
  src/pages/main/ui/page/Page.tsx
  src/shared/components/DropDown.tsx
  src/shared/components/Stars.tsx
  src/shared/components/index.tsx
  tsconfig.json
Labels: ✨ Feature

#29 CODEOWNERS 수정
  .github/CODEOWNERS
Labels: 🔨 Refactor, ⚙️ Setting
