Repository Team-INSERT/IOJ_WEB, pull requests merged in 2024-11, with the labels that each got.

#206 게임 대기실 기능 완성
  src/app/App.tsx
  src/assets/WaitingCharacter.tsx
  src/pages/game/ui/AceEditor/index.tsx
  src/pages/game/ui/editor/index.tsx
  src/pages/room/api/roomApi.ts
  src/pages/room/index.tsx
  src/pages/room/ui/createRoomModal/index.tsx
  src/pages/room/ui/gameFind/index.tsx
  src/pages/waiting/api/enter.ts
  src/pages/waiting/ui/index.tsx
  src/pages/waiting/ui/style.ts
  src/shared/components/InGame/WaitingUser/index.tsx
  src/shared/components/InGame/WaitingUser/style.ts
  src/shared/components/Room/index.tsx
  src/shared/components/Stars.tsx
  src/shared/components/index.tsx
  src/shared/hooks/useWaitingRoom.ts
  src/shared/style/theme.ts
Labels: ✨ Feature, 📪 API

#207 게임 결과 퍼블리싱
  src/app/App.tsx
  src/assets/InGameUserParment.svg
  src/assets/Mini.svg
  src/assets/Podium.svg
  src/assets/Winner.svg
  src/assets/flash.png
  src/pages/game/ui/testbox/index.tsx
  src/pages/result/index.tsx
  src/pages/result/ui/index.tsx
  src/pages/result/ui/style.ts
  src/shared/components/Button.tsx
  src/shared/components/InGame/WaitingUser/style.ts
Labels: ✨ Feature

#220 게임 정보 API 연결
  src/app/App.tsx
  src/pages/game/api/getGameDetails.ts
  src/pages/game/ui/index.tsx
  src/pages/waiting/ui/index.tsx
  src/shared/components/GameHeader/index.tsx
Labels: ✨ Feature, 📪 API

#219 게임 모달 처리 완료
  src/assets/close.svg
  src/pages/waiting/ui/index.tsx
  src/pages/waiting/ui/style.ts
  src/shared/components/ErrorModal.tsx
Labels: ✨ Feature

#218 공격 api 연결
  src/pages/game/api/gameApi.ts
  src/pages/game/ui/chooseAttackModal/index.tsx
Labels: ✨ Feature, 📪 API

#224 아이템 리스트 반환 API 연결
  src/pages/game/api/getItemList.ts
  src/pages/game/ui/chooseAttackModal/index.tsx
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/index.tsx
  src/pages/waiting/ui/index.tsx
  src/shared/components/ItemIconList/index.tsx
Labels: ✨ Feature, 📪 API

#225 아이템 공격 API 연결
  src/pages/game/api/itemAttack.ts
  src/pages/game/ui/chooseAttackModal/index.tsx
  src/pages/game/ui/chooseAttackModal/style.ts
  src/pages/game/ui/index.tsx
  src/pages/room/ui/createRoomModal/index.tsx
  src/shared/components/ItemIcon/index.tsx
  src/shared/components/ItemIconList/index.tsx
  src/shared/utils/atom/roomAtom.ts
Labels: ✨ Feature, 📪 API, 🔮 Modification

#228 실시간 게임 정보 API 연결
  src/pages/game/ui/index.tsx
  src/pages/waiting/ui/index.tsx
  src/shared/components/Item/Mirror.tsx
  src/shared/components/Item/devil/index.tsx
  src/shared/hooks/hook.ts
  src/shared/hooks/useGameInfo.ts
Labels: ✨ Feature, 📪 API

#232 공격 방어 API 연결
  src/pages/game/api/itemDefense.ts
  src/pages/game/ui/index.tsx
  src/shared/components/Item/octopusInk/index.tsx
  src/shared/components/Item/shield/index.tsx
  src/shared/components/Item/waterBalloon/index.tsx
Labels: ✨ Feature, 📪 API

#234 아이템전 게임 화면 나가기 버튼 제거
  src/pages/game/ui/index.tsx
  src/shared/components/GameHeader/index.tsx
Labels: 🔮 Modification

#238 쉴드 아이템 수정
  src/pages/game/ui/index.tsx
  src/shared/components/Item/shield/index.tsx
Labels: 🐞 Bug, 🔥 HotFix, 🔮 Modification

#239 useModal 처리 및 대기실 상태 전처리
  public/index.html
  src/pages/room/api/roomApi.ts
  src/pages/room/ui/createRoomModal/index.tsx
  src/pages/room/ui/createRoomModal/style.ts
  src/pages/room/ui/gameFind/index.tsx
  src/shared/components/ModalWrapper/index.tsx
  src/shared/components/TestModal/index.tsx
  src/shared/components/TestModal/style.ts
  src/shared/hooks/useModal.tsx
  src/shared/utils/protals/ModalPortal.tsx
Labels: ✨ Feature, 📪 API

#244 대마왕 아이템 스페이스 백스페이스 기능 안 바뀜
  src/shared/components/Item/devil/index.tsx
Labels: 🐞 Bug, 🔥 HotFix

#242 물풍선 공격받을 시 코드에디터 클릭 안 되게 설정
  src/pages/game/ui/index.tsx
  src/shared/components/Item/waterBalloon/index.tsx
Labels: ✨ Feature

#249 아이템 경고 색상 진하게
  src/shared/components/Item/warning/index.tsx
Labels: ✨ Feature, 🔮 Modification

#251 코드에디터 공백 삭제
  src/pages/game/ui/index.tsx
Labels: 🐞 Bug, 🔮 Modification

#255 쉴드 클릭 방지
  src/pages/game/ui/index.tsx
  src/shared/components/ItemIcon/index.tsx
  src/shared/components/ItemIcon/style.ts
  src/shared/components/ItemIconList/index.tsx
Labels: 🐞 Bug, ✨ Feature, 🔥 HotFix, 🔮 Modification

#254 물풍선 아이템 공격 시 클릭 안 되게 설정
  src/pages/game/ui/AceEditor/index.tsx
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/index.tsx
Labels: 🐞 Bug, 🔥 HotFix

#258 준비 완료 퍼블리싱 오류 수정
  src/assets/InGameUserParment.svg
  src/assets/close.svg
  src/pages/waiting/ui/index.tsx
  src/pages/waiting/ui/style.ts
  src/shared/components/Button.tsx
  src/shared/components/InGame/WaitingUser/index.tsx
  src/shared/components/InGame/WaitingUser/style.ts
Labels: 🐞 Bug, ✨ Feature, 🔮 Modification

#260 큐 방식으로 공격받은 아이템 저장 및 순차적으로 실행
  src/pages/game/ui/index.tsx
  src/shared/components/Item/Mirror.tsx
  src/shared/components/Item/devil/index.tsx
  src/shared/components/Item/octopusInk/index.tsx
  src/shared/components/Item/waterBalloon/index.tsx
  src/shared/hooks/useGameInfo.ts
Labels: ✨ Feature

#262 에러 모달 네비게이트 수정
  src/pages/room/ui/gameFind/index.tsx
  src/pages/waiting/ui/index.tsx
Labels: 🔥 HotFix, 🔮 Modification

#264 인게임 제출 api 연결 및 대기실 퍼블리싱 수정
  src/pages/game/api/gameSubmit.ts
  src/pages/game/ui/editor/index.tsx
  src/pages/waiting/ui/index.tsx
  src/pages/waiting/ui/style.ts
  src/shared/components/Button.tsx
Labels: ✨ Feature, 📪 API, 🔮 Modification

#265 방 삭제 이벤트 연결
  src/shared/hooks/useWaitingRoom.ts
Labels: 🐞 Bug, ✨ Feature, 🔮 Modification

#267 대마왕 아이템 백스페이스 스페이스 안 바뀜 이슈 해결
  src/pages/game/ui/AceEditor/index.tsx
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/index.tsx
  src/shared/components/Item/devil/index.tsx
Labels: 🐞 Bug, 🔥 HotFix

#269 미러미러 방어실패 추가
  src/pages/game/ui/index.tsx
  src/shared/components/Item/Mirror.tsx
Labels: ✨ Feature, 🔮 Modification

#271 큐에 아이템이 남아 있지만 실행되지 않는 이슈 해결
  src/shared/hooks/useGameInfo.ts
Labels: 🐞 Bug, 🔥 HotFix

#273 게임 결과 페이지 API 연결
  src/app/App.tsx
  src/pages/game/api/gameApi.ts
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/index.tsx
  src/pages/result/api/getItemResult.ts
  src/pages/result/ui/index.tsx
  src/pages/result/ui/style.ts
  src/pages/waiting/ui/index.tsx
  src/pages/waiting/ui/style.ts
  src/shared/components/GameHeader/index.tsx
Labels: ✨ Feature, 🔥 HotFix, 📪 API, 🔮 Modification

#275 코드 실행 입력에러 수정
  .idea/jsLinters/eslint.xml
  .idea/prettier.xml
  src/pages/game/ui/testbox/index.tsx
  src/shared/hooks/useTerminal.ts
Labels: 🐞 Bug, 🔮 Modification

#276 물풍선 공격 쉴드 시 화면 멈추는 에러
  src/pages/game/ui/index.tsx
  src/pages/result/ui/index.tsx
  src/shared/components/GameHeader/index.tsx
Labels: 🐞 Bug, 🔥 HotFix

#279 방생성 모달 유효성 처리
  src/pages/room/ui/createRoomModal/index.tsx
  src/shared/components/ModalWrapper/index.tsx
  src/shared/helper/createRoomHelper.ts
  src/shared/utils/portals/ModalPortal.tsx
Labels: ✨ Feature, 🔮 Modification

#282 물풍선 애니메이션 에러
  src/pages/game/ui/index.tsx
  src/shared/components/Item/waterBalloon/index.tsx
Labels: 🐞 Bug, 🔥 HotFix, 🔮 Modification

#284 아이템 방어 안됨 이슈 해결
  src/pages/game/api/getAttackStart.ts
  src/pages/game/api/itemDefense.ts
  src/pages/game/ui/index.tsx
  src/shared/components/Item/shield/index.tsx
  src/shared/hooks/useGameInfo.ts
Labels: 🐞 Bug, 🔥 HotFix, 📪 API

#292 인게임 저장안됨 수정
  src/pages/game/ui/editor/index.tsx
Labels: 🐞 Bug, ✨ Feature, 🔮 Modification

#294 공격 아이템 방어 안됨 이슈 해결
  src/pages/game/ui/index.tsx
  src/shared/hooks/useGameInfo.ts
Labels: 🐞 Bug, 🔥 HotFix

#297 자잘한 게임 qa 수정
  src/RouteChangeTracker.ts
  src/index.tsx
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/index.tsx
  src/pages/result/ui/detail/index.tsx
  src/pages/result/ui/index.tsx
  src/pages/waiting/ui/index.tsx
  src/shared/components/Room/index.tsx
  src/shared/utils/atom/roomTitelAtom.ts
Labels: 🐞 Bug, 🔥 HotFix, 🔮 Modification

#300 물풍선 아이템 이슈
  src/pages/game/ui/index.tsx
  src/shared/components/Item/waterBalloon/index.tsx
Labels: 🐞 Bug, 🔥 HotFix, 🔮 Modification

#301 미러미러 공격 이후에 너무 늦게 다른 아이템이 실행됨 이슈 해결
  src/pages/game/ui/index.tsx
Labels: 🐞 Bug, 🔥 HotFix

#303 문어먹물이 실행되고 다음 아이템이 대기하고 있다면 문어먹물이 마지막에 줄어들지 않음 이슈 해결
  src/shared/components/Item/octopusInk/index.tsx
Labels: 🐞 Bug, 🔥 HotFix

#306 게임 결과 바로 띄우기
  src/shared/components/GameHeader/index.tsx
Labels: 🐞 Bug, ✨ Feature, 🔥 HotFix

#310 코드저장 안됨, 다른 방 코드 안뜨게 수정
  pnpm-lock.yaml
  src/pages/game/ui/editor/index.tsx
  src/pages/result/ui/index.tsx
Labels: 🐞 Bug, ✨ Feature, 🔮 Modification

#312 방마다 코드저장 초기화 수정
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/index.tsx
  src/pages/main/ui/page/Page.tsx
  src/pages/result/ui/index.tsx
  src/shared/components/MainHeader/index.tsx
  src/shared/utils/auth/authService.ts
Labels: 🔨 Refactor, ✨ Feature, 🔮 Modification

#314 물풍선 터질 때 화면 멈춤 이슈
  src/pages/game/ui/index.tsx
Labels: 🐞 Bug, 🔥 HotFix, 🔮 Modification

#316 퍼블리싱 대거 수정
  src/assets/BlueBg.tsx
  src/assets/GrayBg.tsx
  src/pages/game/ui/testbox/style.ts
  src/pages/room/ui/gameFind/index.tsx
  src/pages/room/ui/gameFind/style.ts
  src/pages/room/ui/gameHome/index.tsx
  src/pages/room/ui/gameHome/style.ts
  src/shared/components/MainHeader/style.ts
  src/shared/components/Room/index.tsx
  src/shared/components/Room/style.ts
Labels: ✨ Feature, 🔮 Modification

#317 아이템전 무적 상태 이슈 해결
  src/shared/hooks/useGameInfo.ts
Labels: 🐞 Bug, 🔥 HotFix

#320 테스트케이스 연속클릭 시 대회 나가짐 수정
  src/pages/game/ui/editor/index.tsx
Labels: 🐞 Bug, 🔮 Modification

#321 제출 버튼 연속 클릭 방지
  src/pages/game/ui/editor/index.tsx
Labels: 🔨 Refactor, ✨ Feature, 🔮 Modification

#323 테스트케이스 스크롤 구현
  src/pages/game/ui/editor/index.tsx
  src/pages/game/ui/editor/style.ts
  src/pages/game/ui/testbox/index.tsx
  src/pages/game/ui/testbox/style.ts
Labels: 🔮 Modification

#326 게임 홈 텍스트 수정
  src/shared/components/GameCard/index.tsx
Labels: 🔥 HotFix

#330 뒤로가기 경로 수정
  src/pages/game/ui/testbox/index.tsx
  src/pages/room/ui/gameFind/index.tsx
Labels: 🐞 Bug
